[package]
name = "test-truck"
version = "0.1.0"
edition = "2021"

[dependencies]
truck-meshalgo = "0.4.0"
truck-modeling = "0.6.0"
truck-polymesh = "0.6.0"
truck-shapeops = "0.4.0"

[profile.release]
opt-level = 3
debug = true
lto = "fat"
codegen-units = 1
#panic = "abort"
